//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicBaseProjectConversionUtility.ProjectConversionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.ImpersonateUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.LocalImpersonationContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.LocalMachineUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.WindowsLoginUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.GuestUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.SessionUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.PasswordCredentialsUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.FacebookCredentialsUserContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.SecuredUserContext))]
    public partial class AbstractUserContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientEventSessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.DisplayType DisplayTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientEventSessionId {
            get {
                return this.ClientEventSessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientEventSessionIdField, value) != true)) {
                    this.ClientEventSessionIdField = value;
                    this.RaisePropertyChanged("ClientEventSessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.DisplayType DisplayType {
            get {
                return this.DisplayTypeField;
            }
            set {
                if ((this.DisplayTypeField.Equals(value) != true)) {
                    this.DisplayTypeField = value;
                    this.RaisePropertyChanged("DisplayType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImpersonateUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class ImpersonateUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext RealUserContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.UserIdentifierType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext RealUserContext {
            get {
                return this.RealUserContextField;
            }
            set {
                if ((object.ReferenceEquals(this.RealUserContextField, value) != true)) {
                    this.RealUserContextField = value;
                    this.RaisePropertyChanged("RealUserContext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.UserIdentifierType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalImpersonationContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class LocalImpersonationContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalMachineUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class LocalMachineUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WindowsLoginUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class WindowsLoginUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuestUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class GuestUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class SessionUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionValue {
            get {
                return this.SessionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionValueField, value) != true)) {
                    this.SessionValueField = value;
                    this.RaisePropertyChanged("SessionValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordCredentialsUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class PasswordCredentialsUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacebookCredentialsUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class FacebookCredentialsUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookID {
            get {
                return this.FacebookIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookIDField, value) != true)) {
                    this.FacebookIDField = value;
                    this.RaisePropertyChanged("FacebookID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecuredUserContext", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class SecuredUserContext : LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuredKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecuredKey {
            get {
                return this.SecuredKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuredKeyField, value) != true)) {
                    this.SecuredKeyField = value;
                    this.RaisePropertyChanged("SecuredKey");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisplayType", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Services." +
        "Folder")]
    public enum DisplayType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Silverlight = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Html = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HtmlWithSilverlight = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HtmlMobile = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HtmlTablet = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentifierType", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    public enum UserIdentifierType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailAddress = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedProject", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConvertedProject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedFlow[] FlowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedForm[] FormsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedRule[] RulesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedFlow[] Flows {
            get {
                return this.FlowsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlowsField, value) != true)) {
                    this.FlowsField = value;
                    this.RaisePropertyChanged("Flows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedForm[] Forms {
            get {
                return this.FormsField;
            }
            set {
                if ((object.ReferenceEquals(this.FormsField, value) != true)) {
                    this.FormsField = value;
                    this.RaisePropertyChanged("Forms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedRule[] Rules {
            get {
                return this.RulesField;
            }
            set {
                if ((object.ReferenceEquals(this.RulesField, value) != true)) {
                    this.RulesField = value;
                    this.RaisePropertyChanged("Rules");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedFlow", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConvertedFlow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedConnection[] ConnectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlowNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.DataDefinition[] InputDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.DataDefinition[] OutputDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedStep[] StepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedConnection[] Connections {
            get {
                return this.ConnectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionsField, value) != true)) {
                    this.ConnectionsField = value;
                    this.RaisePropertyChanged("Connections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlowId {
            get {
                return this.FlowIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FlowIdField, value) != true)) {
                    this.FlowIdField = value;
                    this.RaisePropertyChanged("FlowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlowName {
            get {
                return this.FlowNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FlowNameField, value) != true)) {
                    this.FlowNameField = value;
                    this.RaisePropertyChanged("FlowName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.DataDefinition[] InputData {
            get {
                return this.InputDataField;
            }
            set {
                if ((object.ReferenceEquals(this.InputDataField, value) != true)) {
                    this.InputDataField = value;
                    this.RaisePropertyChanged("InputData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.DataDefinition[] OutputData {
            get {
                return this.OutputDataField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputDataField, value) != true)) {
                    this.OutputDataField = value;
                    this.RaisePropertyChanged("OutputData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedStep[] Steps {
            get {
                return this.StepsField;
            }
            set {
                if ((object.ReferenceEquals(this.StepsField, value) != true)) {
                    this.StepsField = value;
                    this.RaisePropertyChanged("Steps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedForm", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConvertedForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FormDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FormData {
            get {
                return this.FormDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FormDataField, value) != true)) {
                    this.FormDataField = value;
                    this.RaisePropertyChanged("FormData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormId {
            get {
                return this.FormIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FormIdField, value) != true)) {
                    this.FormIdField = value;
                    this.RaisePropertyChanged("FormId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName {
            get {
                return this.FormNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormNameField, value) != true)) {
                    this.FormNameField = value;
                    this.RaisePropertyChanged("FormName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedRule", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConvertedRule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedConnection", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConvertedConnection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SourcePortNumberOnStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStepIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetPortNumberOnStepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetStepIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PathName {
            get {
                return this.PathNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PathNameField, value) != true)) {
                    this.PathNameField = value;
                    this.RaisePropertyChanged("PathName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SourcePortNumberOnStep {
            get {
                return this.SourcePortNumberOnStepField;
            }
            set {
                if ((this.SourcePortNumberOnStepField.Equals(value) != true)) {
                    this.SourcePortNumberOnStepField = value;
                    this.RaisePropertyChanged("SourcePortNumberOnStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceStepId {
            get {
                return this.SourceStepIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStepIdField, value) != true)) {
                    this.SourceStepIdField = value;
                    this.RaisePropertyChanged("SourceStepId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetPortNumberOnStep {
            get {
                return this.TargetPortNumberOnStepField;
            }
            set {
                if ((this.TargetPortNumberOnStepField.Equals(value) != true)) {
                    this.TargetPortNumberOnStepField = value;
                    this.RaisePropertyChanged("TargetPortNumberOnStep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetStepId {
            get {
                return this.TargetStepIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetStepIdField, value) != true)) {
                    this.TargetStepIdField = value;
                    this.RaisePropertyChanged("TargetStepId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataDefinition", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class DataDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanBeNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanBeNull {
            get {
                return this.CanBeNullField;
            }
            set {
                if ((this.CanBeNullField.Equals(value) != true)) {
                    this.CanBeNullField = value;
                    this.RaisePropertyChanged("CanBeNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullTypeName {
            get {
                return this.FullTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullTypeNameField, value) != true)) {
                    this.FullTypeNameField = value;
                    this.RaisePropertyChanged("FullTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsList {
            get {
                return this.IsListField;
            }
            set {
                if ((this.IsListField.Equals(value) != true)) {
                    this.IsListField = value;
                    this.RaisePropertyChanged("IsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConvertedStep", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConvertedStep : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.StepInput[] InputDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.StepOutcome[] OutcomeDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.StepInput[] StepPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueStepIdForConnectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullTypeName {
            get {
                return this.FullTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullTypeNameField, value) != true)) {
                    this.FullTypeNameField = value;
                    this.RaisePropertyChanged("FullTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.StepInput[] InputData {
            get {
                return this.InputDataField;
            }
            set {
                if ((object.ReferenceEquals(this.InputDataField, value) != true)) {
                    this.InputDataField = value;
                    this.RaisePropertyChanged("InputData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.StepOutcome[] OutcomeData {
            get {
                return this.OutcomeDataField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDataField, value) != true)) {
                    this.OutcomeDataField = value;
                    this.RaisePropertyChanged("OutcomeData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StepName {
            get {
                return this.StepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StepNameField, value) != true)) {
                    this.StepNameField = value;
                    this.RaisePropertyChanged("StepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.StepInput[] StepProperties {
            get {
                return this.StepPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.StepPropertiesField, value) != true)) {
                    this.StepPropertiesField = value;
                    this.RaisePropertyChanged("StepProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueStepIdForConnections {
            get {
                return this.UniqueStepIdForConnectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueStepIdForConnectionsField, value) != true)) {
                    this.UniqueStepIdForConnectionsField = value;
                    this.RaisePropertyChanged("UniqueStepIdForConnections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StepInput", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class StepInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.StepInput[] ArrayPartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstantValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.InputMappingType MappingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectValuePathNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.StepInput[] ArrayParts {
            get {
                return this.ArrayPartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrayPartsField, value) != true)) {
                    this.ArrayPartsField = value;
                    this.RaisePropertyChanged("ArrayParts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstantValue {
            get {
                return this.ConstantValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstantValueField, value) != true)) {
                    this.ConstantValueField = value;
                    this.RaisePropertyChanged("ConstantValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraData {
            get {
                return this.ExtraDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraDataField, value) != true)) {
                    this.ExtraDataField = value;
                    this.RaisePropertyChanged("ExtraData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullTypeName {
            get {
                return this.FullTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullTypeNameField, value) != true)) {
                    this.FullTypeNameField = value;
                    this.RaisePropertyChanged("FullTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.InputMappingType MappingType {
            get {
                return this.MappingTypeField;
            }
            set {
                if ((this.MappingTypeField.Equals(value) != true)) {
                    this.MappingTypeField = value;
                    this.RaisePropertyChanged("MappingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectValuePathName {
            get {
                return this.SelectValuePathNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectValuePathNameField, value) != true)) {
                    this.SelectValuePathNameField = value;
                    this.RaisePropertyChanged("SelectValuePathName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StepOutcome", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class StepOutcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicBaseProjectConversionUtility.ProjectConversionService.DataDefinition[] OutcomeDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicBaseProjectConversionUtility.ProjectConversionService.DataDefinition[] OutcomeData {
            get {
                return this.OutcomeDataField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDataField, value) != true)) {
                    this.OutcomeDataField = value;
                    this.RaisePropertyChanged("OutcomeData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PathName {
            get {
                return this.PathNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PathNameField, value) != true)) {
                    this.PathNameField = value;
                    this.RaisePropertyChanged("PathName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputMappingType", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    public enum InputMappingType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectValue = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Constant = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MergeText = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArrayBuilder = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionResult", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ProjectConversion")]
    [System.SerializableAttribute()]
    public partial class ConversionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ConvertedFlowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ConvertedFormsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ConvertedRulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorsOccuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewProjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ConvertedFlows {
            get {
                return this.ConvertedFlowsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConvertedFlowsField, value) != true)) {
                    this.ConvertedFlowsField = value;
                    this.RaisePropertyChanged("ConvertedFlows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ConvertedForms {
            get {
                return this.ConvertedFormsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConvertedFormsField, value) != true)) {
                    this.ConvertedFormsField = value;
                    this.RaisePropertyChanged("ConvertedForms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ConvertedRules {
            get {
                return this.ConvertedRulesField;
            }
            set {
                if ((object.ReferenceEquals(this.ConvertedRulesField, value) != true)) {
                    this.ConvertedRulesField = value;
                    this.RaisePropertyChanged("ConvertedRules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorsOccured {
            get {
                return this.ErrorsOccuredField;
            }
            set {
                if ((this.ErrorsOccuredField.Equals(value) != true)) {
                    this.ErrorsOccuredField = value;
                    this.RaisePropertyChanged("ErrorsOccured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewProjectId {
            get {
                return this.NewProjectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NewProjectIdField, value) != true)) {
                    this.NewProjectIdField = value;
                    this.RaisePropertyChanged("NewProjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FrameworkFault", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
        "")]
    [System.SerializableAttribute()]
    public partial class FrameworkFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectConversionService.IProjectConversionService")]
    public interface IProjectConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectConversionService/UploadConvertedProject", ReplyAction="http://tempuri.org/IProjectConversionService/UploadConvertedProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LogicBaseProjectConversionUtility.ProjectConversionService.FrameworkFault), Action="http://tempuri.org/FrameworkFaultAction", Name="FrameworkFault", Namespace="http://schemas.datacontract.org/2004/07/DecisionsFramework.ServiceLayer.Utilities" +
            "")]
        LogicBaseProjectConversionUtility.ProjectConversionService.ConversionResult UploadConvertedProject(LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext user, LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedProject project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectConversionService/UploadConvertedProject", ReplyAction="http://tempuri.org/IProjectConversionService/UploadConvertedProjectResponse")]
        System.Threading.Tasks.Task<LogicBaseProjectConversionUtility.ProjectConversionService.ConversionResult> UploadConvertedProjectAsync(LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext user, LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedProject project);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectConversionServiceChannel : LogicBaseProjectConversionUtility.ProjectConversionService.IProjectConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectConversionServiceClient : System.ServiceModel.ClientBase<LogicBaseProjectConversionUtility.ProjectConversionService.IProjectConversionService>, LogicBaseProjectConversionUtility.ProjectConversionService.IProjectConversionService {
        
        public ProjectConversionServiceClient() {
        }
        
        public ProjectConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LogicBaseProjectConversionUtility.ProjectConversionService.ConversionResult UploadConvertedProject(LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext user, LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedProject project) {
            return base.Channel.UploadConvertedProject(user, project);
        }
        
        public System.Threading.Tasks.Task<LogicBaseProjectConversionUtility.ProjectConversionService.ConversionResult> UploadConvertedProjectAsync(LogicBaseProjectConversionUtility.ProjectConversionService.AbstractUserContext user, LogicBaseProjectConversionUtility.ProjectConversionService.ConvertedProject project) {
            return base.Channel.UploadConvertedProjectAsync(user, project);
        }
    }
}
